line-length = 100
target-version = "py311"

[lint]
# Base + améliorations utiles sans être lourdes
select = ["E","F","W","I","UP","B","SIM"]
ignore = []

[lint.per-file-ignores]
# Autoriser import non utilisé dans __init__ (exposer API)
"ares/__init__.py" = ["F401"]
