line-length = 120

[lint]
select = ["E","F","W","B","I","UP","SIM"]
ignore = ["E402"]  # on tolère les imports non en tête dans certains scripts Blender/tests

[lint.per-file-ignores]
"tests/**" = ["E402","E501"]
".github/scripts/**" = ["E402"]
"tools/**" = ["E402"]
"ares/modules/**" = ["E501"]
