target-version = "py311"

# Réduire le bruit en attendant le refactor
exclude = [
  "ares/modules/animals",
  "ares/modules/render_bg",
  "ares/modules/turntable",
]

[lint]
# On garde les erreurs importantes…
select = ["E", "F"]
# …mais on ignore celles qui sont surtout stylistiques pour l'instant
ignore = ["E501", "E402", "E401", "F841"]

[lint.per-file-ignores]
"ares/__init__.py" = ["E402"]
"ares/fixbook/__init__.py" = ["E401", "E501"]
"ares/helpers/*.py" = ["E501"]