[tool.ruff]
line-length = 100
target-version = "py311"

# On garde les règles utiles, mais on pose des ignoires par fichier pour le bootstrap actuel.
[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM"]
ignore = []

[tool.ruff.lint.per-file-ignores]
# __init__ de package avec imports bpy/bmesh & defaults Vector → on corrigera plus tard
"ares/__init__.py" = ["E402","B008","B905","SIM105","I001","F841"]
"ares/fixbook/__init__.py" = ["UP009","E401","I001","E501","W292"]
"ares/helpers/__init__.py" = ["I001"]
"ares/helpers/engine.py" = ["I001","W292"]
"ares/helpers/materials.py" = ["I001","E501"]
"ares/helpers/objects.py" = ["I001"]
"ares/modules/__init__.py" = ["UP009","I001","W292"]
"ares/modules/animals/__init__.py" = ["I001"]
"ares/modules/animals/simple.py" = ["I001","F401"]
"ares/modules/render_bg/__init__.py" = ["I001"]
"ares/modules/render_bg/demo.py" = ["I001","F401","E501"]
"ares/modules/render_bg/render_bg.py" = ["I001","UP015","E501"]
"ares/modules/turntable/__init__.py" = ["I001"]
"ares/modules/turntable/turntable.py" = ["I001","F401","E501","F841"]
"ares/modules/turntable_gen.py" = ["UP009","I001","SIM105","W292"]
"ares/ui/panel_turntable.py" = ["I001","SIM105"]

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true
